name: Build with debian
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "ubuntu-24.04-arm"
    steps:
      - name: Test
        run: |
          curl -LO https://github.com/SagerNet/sing-box/releases/download/v1.13.14/sing-box-1.13.14-linux-arm64.tar.gz
          tar -zxf sing-box-1.13.14-linux-arm64.tar.gz
          ./sing-box-1.13.14-linux-arm64/sing-box ech-keypair s3.amazonaws.com >ech.pem
          cat ./ech.pem
